### PR TITLE
README: Use SVG badges

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR changes the build badges to SVG for sharper readability ✨

### CODE REVIEW

**Comment by godfat** [comment]
I wish they look nicer on my browser :o

Before:

screen shot 2018-01-29 at 21 50 01

After:

screen shot 2018-01-29 at 21 50 07

**Comment by olleolleolle** [comment]
@godfat I had no idea this was so - I feel bad for your icons.

**Comment by godfat** [comment]
I think they didn't account for minimum font size, and I have 16pt as the minimum font size. They probably don't care for such minority.

Anyway, SVG should be the future. Let's merge this and hope for the best.

**Comment by lulalala** [comment]
This has been an issue for Chrome in Asian installations since 2010 sigh

https://www.fyianlai.com/2012/01/google-chrome-minimum-font-size-issue/

**Comment by olleolleolle** [comment]
@lulalala ^^ The "I am so sorry" emoticon. Sighing with you.

**Comment by godfat** [comment]
Well, I am on Firefox though. I am so used to broken websites for this, TBH.

**Pull request merged**
